# Ayu Dark Colors for Hyprlock
$bg0    = rgb(0e1419)
$bg1    = rgb(000000)
$bg2    = rgb(1a232c)
$bg3    = rgb(243340)
$bg4    = rgb(3a4a58)

$red    = rgb(ff3333)
$orange = rgb(f19618)
$yellow = rgb(e6c446)
$green  = rgb(b8cc52)
$aqua   = rgb(95e5cb)
$blue   = rgb(36a3d9)
$purple = rgb(f07078)

$fg     = rgb(e5e1cf)

$grey0  = rgb(323232)
$grey1  = rgb(555555)
$grey2  = rgb(e5e1cf)

$fgAlpha     = e5e1cf
$purpleAlpha = f07078
