[colors-dark]
foreground=EEDDBB
background=1A171C
selection-background=584958

## Normal/regular colors (color palette 0-7)
regular0=322932  # black
regular1=DD3014  # red
regular2=5B7035  # green
regular3=D3A03B  # yellow
regular4=4A8494  # blue
regular5=734F70  # magenta
regular6=157F78  # cyan
regular7=EEDDBB  # white

## Bright colors (color palette 8-15)
bright0=584958   # bright black
bright1=DD3014   # bright red
bright2=5B7035   # bright green
bright3=D3A03B   # bright yellow
bright4=4A8494   # bright blue
bright5=734F70   # bright magenta
bright6=157F78   # bright cyan
bright7=E3CEAD   # bright white (using fg1)

## Dimmed colors
dim0=D87948      # orange
dim1=584958      # bg_highlight (Selection bg)
