[colors-dark]
foreground=d4be98
background=282828
selection-background=504945

## Normal/regular colors (color palette 0-7)
regular0=32302f  # black
regular1=ea6962  # red
regular2=a9b665  # green
regular3=d8a657  # yellow
regular4=7daea3  # blue
regular5=d3869b  # magenta
regular6=89b482  # cyan
regular7=d4be98  # white

## Bright colors (color palette 8-15)
bright0=504945   # bright black
bright1=ea6962   # bright red
bright2=a9b665   # bright green
bright3=d8a657   # bright yellow
bright4=7daea3   # bright blue
bright5=d3869b   # bright magenta
bright6=89b482   # bright cyan
bright7=ddc7a1   # bright white

## Dimmed colors
dim0=e78a4e      # orange (Gruvbox Material Peach)
dim1=504945      # bg_highlight (Selection bg)
