# Custom Colors for Kitty
background #040e0d
foreground #f5e2c5
cursor     #f5e2c5
selection_background #1d3631
selection_foreground #f5e2c5

color0  #152a26
color8  #1d3631
color1  #ff6048
color9  #ff6048
color2  #7ad9a8
color10 #7ad9a8
color3  #f5cd5b
color11 #f5cd5b
color4  #5fc8d4
color12 #5fc8d4
color5  #e89aa8
color13 #e89aa8
color6  #3dd1b0
color14 #3dd1b0
color7  #f5e2c5
color15 #e1cdb0
