# Custom Colors for Kitty
background #1A171C
foreground #EEDDBB
cursor     #EEDDBB
selection_background #584958
selection_foreground #EEDDBB

color0  #322932
color8  #584958
color1  #DD3014
color9  #DD3014
color2  #5B7035
color10 #5B7035
color3  #D3A03B
color11 #D3A03B
color4  #4A8494
color12 #4A8494
color5  #734F70
color13 #734F70
color6  #157F78
color14 #157F78
color7  #EEDDBB
color15 #E3CEAD
