[colors-dark]
# Base Theme Colors
background=040e0d
foreground=f5e2c5

## Normal/Regular colors (ANSI 0-7)
regular0=152a26  # bg3 (Dark muted teal)
regular1=ff6048  # red
regular2=7ad9a8  # green
regular3=f5cd5b  # yellow
regular4=5fc8d4  # blue
regular5=e89aa8  # purple
regular6=3dd1b0  # aqua
regular7=f5e2c5  # fg

## Bright/Hover variants (ANSI 8-15)
bright0=1d3631   # bg4 (Slightly lighter container color)
bright1=ff6048   # red
bright2=7ad9a8   # green
bright3=f5cd5b   # yellow
bright4=5fc8d4   # blue
bright5=e89aa8   # purple
bright6=3dd1b0   # aqua
bright7=e1cdb0   # fg1 (Softer foreground variant)

## Miscellaneous
selection-background=1d3631
selection-foreground=f5e2c5
urls=3dd1b0
