# Custom Colors for Hyprlock
$bg0    = rgb(1A171C)
$bg1    = rgb(221C22)
$bg2    = rgb(322932)
$bg3    = rgb(453845)
$bg4    = rgb(584958)

$red    = rgb(DD3014)
$orange = rgb(D87948)
$yellow = rgb(D3A03B)
$green  = rgb(5B7035)
$aqua   = rgb(157F78)
$blue   = rgb(4A8494)
$purple = rgb(734F70)

$fg     = rgb(EEDDBB)

$grey0  = rgb(A88D6F)
$grey1  = rgb(CBB28F)
$grey2  = rgb(E3CEAD)

$fgAlpha     = EEDDBB
$purpleAlpha = 734F70
