# Custom Colors for Hyprlock
$bg0    = rgb(040e0d)
$bg1    = rgb(0a1816)
$bg2    = rgb(0f211f)
$bg3    = rgb(152a26)
$bg4    = rgb(1d3631)

$red    = rgb(ff6048)
$orange = rgb(ffa478)
$yellow = rgb(f5cd5b)
$green  = rgb(7ad9a8)
$aqua   = rgb(3dd1b0)
$blue   = rgb(5fc8d4)
$purple = rgb(e89aa8)

$fg     = rgb(f5e2c5)

$grey0  = rgb(3a1a35)
$grey1  = rgb(5a4d3e)
$grey2  = rgb(c4b09a)

$fgAlpha     = f5e2c5
$purpleAlpha = e89aa8
