[colors-dark]
foreground=e5e1cf
background=0e1419
selection-background=243340

## Normal/regular colors (color palette 0-7)
regular0=000000  # black (bg0)
regular1=ff3333  # red
regular2=b8cc52  # green
regular3=e6c446  # yellow
regular4=36a3d9  # blue
regular5=f07078  # magenta (purple)
regular6=95e5cb  # cyan (aqua)
regular7=ffffff  # white (fg)

## Bright colors (color palette 8-15)
bright0=555555   # bright black (grey0)
bright1=ff6565   # bright red
bright2=e9fe83   # bright green
bright3=fff778   # bright yellow
bright4=68d4ff   # bright blue
bright5=ffa3aa   # bright magenta
bright6=c7fffc   # bright cyan
bright7=ffffff   # bright white (grey2)

## Dimmed colors
dim0=f19618      # orange (cursor color)
dim1=243340      # bg_red (selection background)
